services:

  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped

    ports:
      - "${N8N_PORT}:5678"

    environment:
      - TZ=Europe/Madrid
      - N8N_ENCRYPTION_KEY=jz1ysYPflUCv6lb7qaECy0NzjL351F5k
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
      - N8N_RESTRICT_FILE_ACCESS_TO=/home/node/ggcc_outputs

    volumes:
      - ./data/n8n:/home/node/.n8n
      - ./ggcc_outputs:/home/node/ggcc_outputs

    depends_on:
      - docling
      - qdrant
      - pdf-watermark-cleaner

  pdf-watermark-cleaner:
    build: ./services/pdf_watermark_cleaner
    restart: unless-stopped

    ports:
      - "${PDF_WATERMARK_CLEANER_PORT}:8000"

  docling:
    image: quay.io/docling-project/docling-serve:latest
    restart: unless-stopped

    ports:
      - "${DOCLING_PORT}:5001"

    environment:
      - DOCLING_SERVE_ENABLE_UI=true
      - DOCLING_SERVE_MAX_SYNC_WAIT=600

    volumes:
      - ./data/docling:/data

  qdrant:

    image: qdrant/qdrant:latest

    restart: unless-stopped

    ports:

      - "${QDRANT_PORT}:6333"

    volumes:

      - ./data/qdrant:/qdrant/storage
